services:
    db:
        image: postgres:17.2
        restart: always
        environment:
            POSTGRES_USER: anceda
            POSTGRES_PASSWORD: anceda
            POSTGRES_DB: anceda
        ports:
            - "5432:5432"
        volumes:
            - anceda-data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD", "pg_isready"]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    anceda-data:
